eureka:
  client:
    service-url:
      defaultZone: http://wan:wan@localhost:7777/eureka/
  instance:
    hostname: localhost
  server:
    eviction-interval-timer-in-ms: 1000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
      isolation:
        thread:
          timeoutInMilliseconds: 60000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

feign:
  hystrix:
    enabled: true
## 刷新时，关闭安全验证
management:
  security:
    enabled: false

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://172.20.24.29:3306/wx?createDatabaseIfNotExist=true&useSSL=false&characterEncoding=utf8&useUnicode=true
    tomcat:
      max-active: 200
      max-idle: 30
      min-idle: 5
      test-on-borrow: true
      validation-query: select 1
      time-between-eviction-runs-millis: 360000
      initial-size: 5
    servlet:
      multipart:
        max-request-size: 50MB
        max-file-size: 50MB
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
      hibernate.show_sql: true
      hibernate.format_sql: true
      hibernate.use_sql_comments: true
      hibernate.hbm2ddl.auto: update
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 30000
      password: 123456
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
pagehelper:
  autoDialect: true
  closeConn: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true


weixin:
  appId: wxd6feee8620d649a0
  secret: 71eba3bb354255d423151c36828ad12e
  token: wanzhong
  aesKey: UIU7XGXUAwlZkJ2hGyyOP2kq4OcYqOTcEKDhn6cS8fn
  accessToken: 3
  expiresIn: r
  openId: 3
  urls:
    ## 获取access_token,微信接口
    get_access_token: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid={appid}&secret={secret}
    get_open_id: https://api.weixin.qq.com/cgi-bin/user/info?access_token={access_token}&openid={openid}&lang=zh_CN